### ISSUE TITLE
Issue with starting server

### ISSUE THREAD

**Issue by benawi92** [jpwright/enmodal#23]
Hi,
I'm experiencing issues with starting the server. Every time I enter the command python server.py, I get the error message 
Traceback (most recent call last):
  File "server.py", line 92, in <module>
    os.mkdir(UPLOAD_FOLDER)
WindowsError: [Error 3] The system cannot find the path specified: 'enmodal/uploads'

I'm not sure what to do to resolve this.
Thank you.

**Comment by Jdekoning141** [comment]
Hi, i personally had the same issue, and as it turned out, in the settings.cfg file in the root 'enmodal' folder, there's this line "upload_folder = 'enmodal/uploads'". Windows does not like this, you need to put in an absolute path. for me this was. C:/Users/<username>/enmodal/uploads/. I had to create the uploads folder manually as well. server started fine after that.

**Comment by Jdekoning141** [comment]
Another two notes:

After installation, you'll need to go into the venv/app-packages/flask folder and open app.py for editing. You'll need to find the section where config options are set, inbetween there is the server_name

**Comment by benawi92** [comment]
That worked, thank you!
