### ISSUE TITLE
Python Incompatibility

### ISSUE THREAD

**Issue by DaMarMan111** [jpwright/enmodal#34]
Python 2.7 has apparently shut down so when I got to run the server there's an error. Is there a way to make this compatible with Python 3.0? I'm on Mac btw.

**Comment by Dezlite** [comment]
I'm in a similar situation as you are. I was trying to get this working on my WIndows, and Python 2.7 isn't working because I can't get PIP to be incorporated with it. Python 2.7 doesn't have PIP bundled with it, so you have to manually get PIP by downloading a file called `get-pip.py` and run the `python get-pip.py` command. When I did that, it told me `DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.` So that means Python 2.7 is pointless. I tried version 3.9.1, and I got very far, but then I got a large error after typing in the `pip install -r requirements.txt` step. It might not be possible to get this working anymore.

**Comment by jpwright** [comment]
The latest master works with python3.

**Comment by DaMarMan111** [comment]
i downloaded python 3 and tried again but i got this after running the command "pip install -r requirements.txt"

`DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'`

**Comment by jpwright** [comment]
@DaMarMan111 It sounds like you still have Python 2.7 installed on your system. Uninstall Python 2.7 and make sure your system PATH points to your Python 3 installation.

**Comment by DaMarMan111** [comment]
I did that and im now getting this when trying to install virtualenv

`The directory '/Users/Marcos/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.`

**Comment by jpwright** [comment]
You can actually skip that step and just run `python3 -m venv venv`. Been a while since I tested this on Mac though and those instructions need updating. Going to close this thread, please start a new one with any further issues.
